config/routes.rb
Rails.application.routes.draw do
  get 'categories/show'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "books#index"
  resources :books
  devise_for :users
  resources :users
  resources :categories
  namespace :api, defaults: {format: :json} do
    scope module: :v1 do
      resources :users
      resources :books
    end
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books
  validates :name, presence: true, length: {minimum: 5}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/books_controller.rb
class Api::V1::BooksController  < ApplicationController
  skip_before_filter  :verify_authenticity_token
  respond_to  :json

  def index
    render json: Book.all
  end


  def show
    respond_with  Book.find(params[:id])
  end

  def create
    book  = Book.new(book_params)
    if  book.save
      render  json: book, status: 201,  location: [:api,  book]
    else
      render  json: { errors: book.errors },  status: 422
    end
  end

  def update
    book  = Book.find(params[:id])
    if  book.update(book_params)
      render  json: book, status: 200,  location: [:api,  book]
    else
      render  json: { errors: book.errors },  status: 422
    end
  end

  def destroy
    book  = Book.find(params[:id])
    book.destroy
    head  204
  end

  private
  def book_params
    params.require(:book).permit(:name,  :description,  :author, :category, :publish_year, :image)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController  < ApplicationController
  skip_before_filter  :verify_authenticity_token
  respond_to  :json
  def show
    respond_with  User.find(params[:id])
  end

  def create
    user  = User.new(user_params)
    if  user.save
      render  json: user, status: 201,  location: [:api,  user]
    else
      render  json: { errors: user.errors },  status: 422
    end
  end

  def update
    user  = User.find(params[:id])
    if  user.update(user_params)
      render  json: user, status: 200,  location: [:api,  user]
    else
      render  json: { errors: user.errors },  status: 422
    end
  end

  def destroy
    user  = User.find(params[:id])
    user.destroy
    head  204
  end

  private
    def user_params
      params.require(:user).permit(:email,  :password,  :password_confirmation)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find params[:id]
    @books = @category.books
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = "UET Library"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<div class="col-md-2">
  <%= link_to book do %>
    <div class="thumbnail">
    <%= image_tag book.image, size: "150x200" %>
    <% if book.name.length >25 %>
      <%= book.name.split.map(&:capitalize).join(' ')[0..25] %>...
    <% else %>
      <%= book.name.split.map(&:capitalize).join(' ') %>
    <% end %>
    </div>
  <% end %>
</div>

app/views/books/index.html.erb
<% provide :title, "Home" %>
<div class="row", style="padding_top: 30px">
  <%= render @books %>
</div>

app/views/books/show.html.erb
<% provide :title, @book.name %>

<div class="row">
  <aside class="col-md-3">
    <%= image_tag @book.image, size: "150x200" %>
  </aside>
  <aside class="col-md-9">
    <h3><%= @book.name %></h3>
    <h5> by <%= @book.author %></h5>
    <h3>Details here</h3>
    Name: <%= @book.name.split.map(&:capitalize).join(' ') %><br>
    Description: <%= @book.description %>
  </aside>
</div>

app/views/categories/show.html.erb
<% provide :title, @category.name %>
<div class="row">
  <%= render @books %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About us", "#" %></li>
      <li><%= link_to "Contact", "#" %></li>
    </ul
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "UET Library", root_path, id: "logo" %>
    <ul class="nav navbar-nav navbar-left">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Category <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "Books", books_path %></li>
          <li class="divider"></li>
          <% Category.all.each do |category| %>
            <li><%= link_to category.name, category_path(category) %></li>
            <li class="divider"></li>
          <% end %>
        </ul>
      </li>
    </ul>

    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("links.home"), root_path %></li>
        <li><%= link_to t("links.help"), "#" %></li>

      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :defaults, "http://localhost:9292/faye.js" %>
  <%= csrf_meta_tags %>
  <%= render "layouts/shim" %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
    <%#= render "layouts/footer" %>
  </div>
</body>
</html>

app/views/staticpages/home.html.erb
<h1>Staticpages#home</h1>
<p>Find me in app/views/staticpages/home.html.erb</p>